# Generated by Django 5.1.2 on 2024-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('release_date', models.DateField()),
                ('num_pages', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
